name: farmswap_v2
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  provider: ^6.0.5
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/onboarding/
    - assets/svg/auth/
    - assets/svg/bio/
    - assets/svg/success/
    - assets/svg/upload photo/
    - assets/svg/forgot password/
    - assets/svg/dashboard/
    - assets/images/
    - assets/images/png/
    - assets/images/category/
    - assets/images/dummy/
    - assets/images/payment badges/
