name: farmswap_v2
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  provider: ^6.0.5
  pin_code_fields: ^8.0.1
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  firebase_messaging: ^14.6.8
  firebase_in_app_messaging: ^0.7.3+6
  firebase_storage: ^11.2.7
  supabase_flutter: ^1.10.19
  flutter_screenutil: ^5.9.0
  auth_buttons: ^3.0.2
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/logo/svg/
    - assets/svg/logo/png/
    - assets/svg/onboarding/
    - assets/svg/auth/
    - assets/svg/bio/
    - assets/svg/success/
    - assets/svg/upload photo/
    - assets/svg/forgot password/
    - assets/svg/dashboard/
    - assets/svg/bottom nav/
    - assets/images/
    - assets/images/png/
    - assets/images/category/
    - assets/images/dummy/
    - assets/images/listing/
    - assets/images/payment badges/
    - assets/images/logo/
