// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH_x4XHqGnzdjoe8OwCpeaQ6u9TWtQ3Ec',
    appId: '1:1095006869916:web:247631b47d516f63091059',
    messagingSenderId: '1095006869916',
    projectId: 'farmswap-678f3',
    authDomain: 'farmswap-678f3.firebaseapp.com',
    storageBucket: 'farmswap-678f3.appspot.com',
    measurementId: 'G-CRW82P72M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeprMtzOTSFl_RH3CLRtI05OoZchmlS3U',
    appId: '1:1095006869916:android:ffce1a62daa49815091059',
    messagingSenderId: '1095006869916',
    projectId: 'farmswap-678f3',
    storageBucket: 'farmswap-678f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfrBabOlBSpxStMbEk5LeLN31afB2QwO4',
    appId: '1:1095006869916:ios:0d0900ed61623739091059',
    messagingSenderId: '1095006869916',
    projectId: 'farmswap-678f3',
    storageBucket: 'farmswap-678f3.appspot.com',
    iosBundleId: 'ph.farmswap.farmswapV2',
  );
}
